version: '3.8'

services:
  web:
    build: .
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=roundhouse.proxy.rlwy.net
      - DB_PORT=53352
      - DB_DATABASE=railway
      - DB_USERNAME=root
      - DB_PASSWORD=KNFAvVvdVOwmFBqJApVRuGPFPsEOjbwe
